"""Causal technical baseline backtest for FAST_SCALP_M1.

This replays MT5-exported M1 OHLC/spread data. Direction is generated by the
same FAST_SCALP_M1 Python engine using completed M1 candles and only fully
completed M5 closes. Historical news is not reconstructed, so this is a
technical/execution baseline rather than proof of live performance.
"""

from __future__ import annotations

import argparse
import math
from collections import Counter
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

from meta_trader_ai.backtest import Candle, load_candles
from meta_trader_ai.fast_scalp import FastScalpSnapshot, build_fast_scalp_hint
from meta_trader_ai.models import Action, NewsCoverage


@dataclass(frozen=True, slots=True)
class FastScalpBacktestParameters:
    risk_percent: float = 0.25
    reward_risk_ratio: float = 1.50
    max_open_positions: int = 2
    max_daily_loss_percent: float = 1.0
    max_spread_atr_ratio: float = 0.18
    min_confidence: int = 72
    atr_period: int = 14
    atr_multiplier: float = 1.0
    min_stop_points: float = 80.0
    max_stop_points: float = 500.0
    m1_lookback_bars: int = 120
    m5_lookback_bars: int = 60

    def validate(self) -> None:
        if not 0.0 < self.risk_percent <= 0.5:
            raise ValueError("risk_percent must be > 0 and <= 0.5")
        if self.reward_risk_ratio <= 0.0:
            raise ValueError("reward_risk_ratio must be positive")
        if self.max_open_positions < 1:
            raise ValueError("max_open_positions must be positive")
        if self.max_daily_loss_percent <= 0.0:
            raise ValueError("max_daily_loss_percent must be positive")
        if not 0 <= self.min_confidence <= 100:
            raise ValueError("min_confidence must be between 0 and 100")
        if self.atr_period < 2 or self.atr_multiplier <= 0.0:
            raise ValueError("ATR settings are invalid")
        if self.min_stop_points <= 0 or self.max_stop_points < self.min_stop_points:
            raise ValueError("stop settings are invalid")
        if self.m1_lookback_bars < 30 or self.m5_lookback_bars < 20:
            raise ValueError("lookback settings are too short")


@dataclass(slots=True)
class _OpenScalp:
    action: Action
    signal_time: datetime
    entry_time: datetime
    confidence: int
    technical_score: int
    entry_price: float
    stop_price: float
    target_price: float
    stop_points: float
    risk_money: float


@dataclass(frozen=True, slots=True)
class FastScalpBacktestTrade:
    signal_time: datetime
    entry_time: datetime
    exit_time: datetime
    action: Action
    confidence: int
    technical_score: int
    entry_price: float
    stop_price: float
    target_price: float
    exit_price: float
    risk_money: float
    pnl_r: float
    pnl_usd: float
    outcome: str
    balance_after: float


@dataclass(frozen=True, slots=True)
class FastScalpBacktestMetrics:
    start_balance: float
    end_balance: float
    net_usd: float
    return_percent: float
    trades: int
    wins: int
    losses: int
    win_rate: float
    profit_factor: float
    expectancy_r: float
    net_r: float
    max_drawdown_usd: float
    max_drawdown_r: float
    max_concurrent_positions_seen: int


@dataclass(frozen=True, slots=True)
class FastScalpBacktestResult:
    trades: list[FastScalpBacktestTrade]
    metrics: FastScalpBacktestMetrics
    blocked: Counter[str]


def _bucket_m5(value: datetime) -> tuple[int, int, int, int, int]:
    return (
        value.year,
        value.month,
        value.day,
        value.hour,
        value.minute // 5,
    )


def _atr(candles: list[Candle], period: int) -> float:
    true_ranges: list[float] = []
    for index in range(1, len(candles)):
        current = candles[index]
        previous_close = candles[index - 1].close
        true_ranges.append(
            max(
                current.high - current.low,
                abs(current.high - previous_close),
                abs(current.low - previous_close),
            )
        )
    sample = true_ranges[-period:]
    return max(sum(sample) / len(sample), 1e-12) if sample else 1e-12


def _exit_on_bar(
    position: _OpenScalp,
    candle: Candle,
    *,
    point_size: float,
) -> tuple[str, float] | None:
    spread = candle.spread_points * point_size
    if position.action is Action.BUY:
        stop_hit = candle.low <= position.stop_price
        target_hit = candle.high >= position.target_price
    else:
        ask_high = candle.high + spread
        ask_low = candle.low + spread
        stop_hit = ask_high >= position.stop_price
        target_hit = ask_low <= position.target_price

    # M1 OHLC does not reveal intrabar ordering. STOP-first is conservative.
    if stop_hit:
        return "STOP", position.stop_price
    if target_hit:
        return "TARGET", position.target_price
    return None


def _pnl_r(position: _OpenScalp, exit_price: float, point_size: float) -> float:
    stop_distance = position.stop_points * point_size
    pnl_price = (
        exit_price - position.entry_price
        if position.action is Action.BUY
        else position.entry_price - exit_price
    )
    return pnl_price / max(stop_distance, 1e-12)


def _calculate_metrics(
    trades: list[FastScalpBacktestTrade],
    *,
    start_balance: float,
    end_balance: float,
    max_concurrent_positions_seen: int,
) -> FastScalpBacktestMetrics:
    wins = [item for item in trades if item.pnl_r > 1e-12]
    losses = [item for item in trades if item.pnl_r < -1e-12]
    gross_profit_r = sum(item.pnl_r for item in wins)
    gross_loss_r = abs(sum(item.pnl_r for item in losses))
    if gross_loss_r > 0.0:
        profit_factor = gross_profit_r / gross_loss_r
    elif gross_profit_r > 0.0:
        profit_factor = math.inf
    else:
        profit_factor = 0.0

    cumulative_r = 0.0
    peak_r = 0.0
    max_drawdown_r = 0.0
    peak_balance = start_balance
    max_drawdown_usd = 0.0
    for trade in trades:
        cumulative_r += trade.pnl_r
        peak_r = max(peak_r, cumulative_r)
        max_drawdown_r = max(max_drawdown_r, peak_r - cumulative_r)
        peak_balance = max(peak_balance, trade.balance_after)
        max_drawdown_usd = max(max_drawdown_usd, peak_balance - trade.balance_after)

    net_r = sum(item.pnl_r for item in trades)
    net_usd = end_balance - start_balance
    return FastScalpBacktestMetrics(
        start_balance=start_balance,
        end_balance=end_balance,
        net_usd=net_usd,
        return_percent=net_usd / start_balance * 100.0,
        trades=len(trades),
        wins=len(wins),
        losses=len(losses),
        win_rate=len(wins) / len(trades) * 100.0 if trades else 0.0,
        profit_factor=profit_factor,
        expectancy_r=net_r / len(trades) if trades else 0.0,
        net_r=net_r,
        max_drawdown_usd=max_drawdown_usd,
        max_drawdown_r=max_drawdown_r,
        max_concurrent_positions_seen=max_concurrent_positions_seen,
    )


def simulate_fast_scalp(
    candles: list[Candle],
    *,
    symbol: str = "XAUUSD_o",
    point_size: float = 0.01,
    initial_balance: float = 1_000.0,
    params: FastScalpBacktestParameters | None = None,
) -> FastScalpBacktestResult:
    """Replay the M1 profile causally with up to the configured open positions."""
    cfg = params or FastScalpBacktestParameters()
    cfg.validate()
    if point_size <= 0.0 or initial_balance <= 0.0:
        raise ValueError("point_size and initial_balance must be positive")
    if len(candles) < cfg.m1_lookback_bars + 2:
        raise ValueError("Not enough M1 candles for the configured lookback")

    balance = initial_balance
    day_start_balance = initial_balance
    current_day = candles[0].time.date()
    m5_closes: list[float] = []
    open_positions: list[_OpenScalp] = []
    trades: list[FastScalpBacktestTrade] = []
    blocked: Counter[str] = Counter()
    max_concurrent = 0

    def close_position(
        position: _OpenScalp,
        candle: Candle,
        outcome: str,
        exit_price: float,
    ) -> None:
        nonlocal balance
        pnl_r = _pnl_r(position, exit_price, point_size)
        pnl_usd = position.risk_money * pnl_r
        balance += pnl_usd
        trades.append(
            FastScalpBacktestTrade(
                signal_time=position.signal_time,
                entry_time=position.entry_time,
                exit_time=candle.time,
                action=position.action,
                confidence=position.confidence,
                technical_score=position.technical_score,
                entry_price=position.entry_price,
                stop_price=position.stop_price,
                target_price=position.target_price,
                exit_price=exit_price,
                risk_money=position.risk_money,
                pnl_r=pnl_r,
                pnl_usd=pnl_usd,
                outcome=outcome,
                balance_after=balance,
            )
        )

    start_index = cfg.m1_lookback_bars
    for entry_index in range(1, len(candles)):
        current = candles[entry_index]
        previous = candles[entry_index - 1]

        if _bucket_m5(current.time) != _bucket_m5(previous.time):
            m5_closes.append(previous.close)

        if current.time.date() != current_day:
            current_day = current.time.date()
            day_start_balance = balance

        if entry_index < start_index or len(m5_closes) < 20:
            continue

        # The slot check is made at the M1 open, before using this candle's high/low.
        # That avoids look-ahead from an intrabar exit that has not happened yet.
        slot_available_at_open = len(open_positions) < cfg.max_open_positions

        m1_window = candles[
            max(0, entry_index - cfg.m1_lookback_bars) : entry_index
        ]
        m5_window = m5_closes[-cfg.m5_lookback_bars :]
        signal_candle = previous
        signal_spread = signal_candle.spread_points * point_size
        snapshot = FastScalpSnapshot(
            symbol=symbol,
            timeframe="PERIOD_M1",
            generated_at=signal_candle.time,
            bid=signal_candle.close,
            ask=signal_candle.close + signal_spread,
            balance=balance,
            equity=balance,
            positions_total=len(open_positions),
            day_start_balance=day_start_balance,
            day_realized_pnl=balance - day_start_balance,
            opens=[item.open for item in m1_window],
            highs=[item.high for item in m1_window],
            lows=[item.low for item in m1_window],
            closes=[item.close for item in m1_window],
            tick_volumes=[item.tick_volume for item in m1_window],
            m5_closes=m5_window,
        )
        hint = build_fast_scalp_hint(
            snapshot,
            [],
            max_risk_percent=cfg.risk_percent,
            max_open_positions=cfg.max_open_positions,
            max_daily_loss_percent=cfg.max_daily_loss_percent,
            max_spread_atr_ratio=cfg.max_spread_atr_ratio,
            min_confidence=cfg.min_confidence,
            news_coverage=NewsCoverage.COMPLETE,
        )

        if hint.action not in {Action.BUY, Action.SELL}:
            blocked[hint.risk_guard_status.lower()] += 1
        elif not slot_available_at_open:
            blocked["position_limit_at_open"] += 1
        else:
            atr = _atr(m1_window, cfg.atr_period)
            spread_price = current.spread_points * point_size
            spread_to_atr = spread_price / max(atr, 1e-12)
            if spread_to_atr > cfg.max_spread_atr_ratio:
                blocked["entry_spread"] += 1
            else:
                stop_points = max(
                    cfg.min_stop_points,
                    atr * cfg.atr_multiplier / point_size,
                )
                if stop_points > cfg.max_stop_points:
                    blocked["stop_too_wide"] += 1
                else:
                    entry_price = (
                        current.open + spread_price
                        if hint.action is Action.BUY
                        else current.open
                    )
                    target_points = stop_points * cfg.reward_risk_ratio
                    if hint.action is Action.BUY:
                        stop_price = entry_price - stop_points * point_size
                        target_price = entry_price + target_points * point_size
                    else:
                        stop_price = entry_price + stop_points * point_size
                        target_price = entry_price - target_points * point_size

                    open_positions.append(
                        _OpenScalp(
                            action=hint.action,
                            signal_time=signal_candle.time,
                            entry_time=current.time,
                            confidence=hint.confidence,
                            technical_score=hint.technical_score,
                            entry_price=entry_price,
                            stop_price=stop_price,
                            target_price=target_price,
                            stop_points=stop_points,
                            risk_money=balance * cfg.risk_percent / 100.0,
                        )
                    )
                    max_concurrent = max(max_concurrent, len(open_positions))

        survivors: list[_OpenScalp] = []
        for position in open_positions:
            resolved = _exit_on_bar(position, current, point_size=point_size)
            if resolved is None:
                survivors.append(position)
                continue
            close_position(position, current, resolved[0], resolved[1])
        open_positions = survivors

    if open_positions:
        final = candles[-1]
        spread = final.spread_points * point_size
        for position in open_positions:
            exit_price = (
                final.close
                if position.action is Action.BUY
                else final.close + spread
            )
            close_position(position, final, "END_OF_WINDOW", exit_price)

    metrics = _calculate_metrics(
        trades,
        start_balance=initial_balance,
        end_balance=balance,
        max_concurrent_positions_seen=max_concurrent,
    )
    return FastScalpBacktestResult(
        trades=trades,
        metrics=metrics,
        blocked=blocked,
    )


def render_report(result: FastScalpBacktestResult) -> str:
    metrics = result.metrics
    pf = "inf" if math.isinf(metrics.profit_factor) else f"{metrics.profit_factor:.3f}"
    top_blocked = ", ".join(
        f"{key}={value}" for key, value in result.blocked.most_common(8)
    ) or "none"
    return "\n".join(
        [
            "META TRADER AI - FAST_SCALP_M1 TECHNICAL BACKTEST",
            "=" * 76,
            f"Trades: {metrics.trades} | Wins: {metrics.wins} | Losses: {metrics.losses}",
            f"Win rate: {metrics.win_rate:.2f}% | Profit factor: {pf}",
            f"Expectancy: {metrics.expectancy_r:+.3f}R/trade | Net: {metrics.net_r:+.2f}R",
            f"Balance: ${metrics.start_balance:.2f} -> ${metrics.end_balance:.2f} "
            f"({metrics.return_percent:+.2f}%)",
            f"Max DD: {metrics.max_drawdown_r:.2f}R / ${metrics.max_drawdown_usd:.2f}",
            f"Max concurrent positions seen: {metrics.max_concurrent_positions_seen}",
            f"Top blocked reasons: {top_blocked}",
            "Historical news and exact tick ordering are not reconstructed.",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Backtest FAST_SCALP_M1 on MT5 M1 CSV")
    parser.add_argument("csv", type=Path, help="Path to xauusd_m1_history.csv")
    parser.add_argument("--symbol", default="XAUUSD_o")
    parser.add_argument("--point-size", type=float, default=0.01)
    parser.add_argument("--balance", type=float, default=1_000.0)
    parser.add_argument("--max-positions", type=int, default=2)
    parser.add_argument("--risk-percent", type=float, default=0.25)
    args = parser.parse_args()

    candles = load_candles(args.csv)
    params = FastScalpBacktestParameters(
        max_open_positions=args.max_positions,
        risk_percent=args.risk_percent,
    )
    result = simulate_fast_scalp(
        candles,
        symbol=args.symbol,
        point_size=args.point_size,
        initial_balance=args.balance,
        params=params,
    )
    print(render_report(result))


if __name__ == "__main__":
    main()
